SET FOREIGN_KEY_CHECKS=0;
--

TRUNCATE TABLE OFERTAS;
ALTER TABLE OFERTAS ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE PRODUTOS;
ALTER TABLE PRODUTOS ALTER COLUMN ID RESTART WITH 1;

--
SET FOREIGN_KEY_CHECKS=1;